name: ci

on:
    push:
        branches:
            - 'main'

jobs:
    docker:
        runs-on: ubuntu-lastest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build and push Docker images
              uses: docker/build-push-action@v1  
              with:
                username: ${{ secret.DOCKER_USERNAME }}
                password: ${{ secret.DOCKER_PASSWORD }}
                tag_with_ref: true
                tag_with_sha: true
                tags: edu20/landing-page:${{ github.sha }}