name: ci

on:
    push:
        branches:
            - 'main'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - 
              name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - 
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            -
              name: Login to DockerHub
              uses: docker/login-action@1    
              with:
                username: ${{ secret.DOCKER_USERNAME }}
                password: ${{ secret.DOCKER_PASSWORD }}
            -
              name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: edu20/probando-github-actions:${{ github.sha }}
            -
              name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest}}